name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig: ["0.14.0", "0.15.0-dev.441+c1649d586"]

    runs-on: ${{matrix.os}}

    steps:
    - name: Clone Ziglua
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ matrix.zig }}

    - name: Run tests
      run: make test

  test_cross:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig: ["0.14.0", "0.15.0-dev.441+c1649d586"]

    runs-on: ${{matrix.os}}

    steps:
    - name: Clone Ziglua
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ matrix.zig }}

    - name: Run tests
      run: make test_cross